version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: matchtracker
      POSTGRES_USER: matchuser
      POSTGRES_PASSWORD: matchpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - match-network

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/matchtracker
      SPRING_DATASOURCE_USERNAME: matchuser
      SPRING_DATASOURCE_PASSWORD: matchpass
    depends_on:
      - db
    networks:
      - match-network

networks:
  match-network:

volumes:
  pgdata:
